package co.typecheck.adventofcode2024

import kotlin.test.Test
import kotlin.test.assertEquals

class Day08Test {

    @Test
    fun day08Part1() {
        assertEquals(
            14,
            day08Part1(
                """
                    ............
                    ........0...
                    .....0......
                    .......0....
                    ....0.......
                    ......A.....
                    ............
                    ............
                    ........A...
                    .........A..
                    ............
                    ............
                """.trimIndent(),
            ),
        )
    }

    @Test
    fun day08Part2() {
        assertEquals(
            34,
            day08Part2(
                """
                    ............
                    ........0...
                    .....0......
                    .......0....
                    ....0.......
                    ......A.....
                    ............
                    ............
                    ........A...
                    .........A..
                    ............
                    ............
                """.trimIndent(),
            ),
        )
    }
}